# Generated by Django 4.0.3 on 2022-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savenature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=1000)),
                ('amount', models.CharField(max_length=500)),
                ('paymentid', models.CharField(max_length=1000)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
