# Generated by Django 4.0.3 on 2022-03-12 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savenatureapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savenature',
            old_name='phonenumber',
            new_name='name',
        ),
        migrations.AddField(
            model_name='savenature',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
