# Generated by Django 4.0.3 on 2022-03-18 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savenatureapp', '0002_rename_phonenumber_savenature_name_savenature_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='savenature',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
